import Link from "next/link";
import { PageHeader } from "@/components/page-header";

interface Props {
  params: Promise<{ id: string; tab: string }>;
}

const tabConfig: Record<string, { category: string; title: string; description: string }> = {
  stakeholders: { category: "Identity & DNA", title: "Stakeholder NFTs", description: "Ownership registry and revenue distribution for world stakeholders." },
  dna: { category: "Identity & DNA", title: "DNA Evolution", description: "Track mutations, adaptations, and genetic drift in world parameters over time." },
  lineage: { category: "Identity & DNA", title: "World Lineage", description: "Ancestry, fork history, and generational relationships between worlds." },
  governance: { category: "Governance & Events", title: "Governance", description: "Active proposals, voting history, and constitutional parameters." },
  events: { category: "Governance & Events", title: "World Events", description: "Scheduled and spontaneous events shaping world state." },
  history: { category: "Governance & Events", title: "History Ledger", description: "An immutable chronological record of every significant world event." },
  zones: { category: "World Systems", title: "World Zones", description: "Geographic and conceptual partitions governing physics and economics." },
  physics: { category: "World Systems", title: "World Physics", description: "Physical laws, constants, and simulation parameters active in this world." },
  "physics-stress": { category: "World Systems", title: "Physics Stress Test", description: "Load testing the physics engine under extreme entity density." },
  "time-compression": { category: "World Systems", title: "Time Compression", description: "Control the rate at which simulated time progresses relative to real time." },
  "npc-society": { category: "AI & Civilization", title: "NPC Society", description: "The social structures, factions, and relationships of AI-driven inhabitants." },
  "npc-economics": { category: "AI & Civilization", title: "NPC Economics", description: "Economic behavior, trade patterns, and resource allocation of NPC agents." },
  civilization: { category: "AI & Civilization", title: "AI Civilization", description: "Emergent civilizations, their cultures, and long-term developmental arcs." },
  mythology: { category: "AI & Civilization", title: "Cultural Mythology", description: "Stories, beliefs, and cultural artifacts generated by AI inhabitants." },
  scars: { category: "Economy", title: "Economic Scars", description: "Lasting economic trauma events and their cascading effects on world health." },
  commerce: { category: "Economy", title: "Commerce Hooks", description: "Integration points for external commerce systems and marketplace APIs." },
  vr: { category: "VR & Hardware", title: "VR Presence", description: "Immersive presence configuration and headset compatibility settings." },
  "live-events": { category: "VR & Hardware", title: "VR Live Events", description: "Scheduled multi-user events accessible via VR headsets." },
  "events-bridge": { category: "VR & Hardware", title: "Events Bridge", description: "Real-world event integration piped into world state as native events." },
  "vr-tooling": { category: "VR & Hardware", title: "VR Creator Tooling", description: "In-world creation tools accessible from within a VR headset." },
  tickets: { category: "VR & Hardware", title: "VR Ticketing", description: "Access control and admission management for VR-gated world experiences." },
  "stress-test": { category: "Testing & Development", title: "Stress Testing", description: "Automated load scenarios to validate world stability under peak conditions." },
  "load-test": { category: "Testing & Development", title: "Load Testing", description: "Measure throughput and latency under sustained simulation load." },
};

export default async function WorldTabPage({ params }: Props) {
  const { id, tab } = await params;
  const config = tabConfig[tab] ?? {
    category: "World",
    title: tab.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
    description: "World feature panel.",
  };

  return (
    <div className="mx-auto max-w-7xl px-6 py-12">
      <div className="mb-8 flex items-center gap-2 font-mono text-xs text-white/30">
        <Link href={`/world/${id}`} className="hover:text-white transition-colors">
          {id === "demo" ? "Meridian-7" : id}
        </Link>
        <span>/</span>
        <span className="text-white/50">{config.title}</span>
      </div>

      <PageHeader
        category={config.category}
        title={config.title}
        description={config.description}
      />

      <div className="border border-white/10 p-12">
        <div className="mb-4 font-mono text-xs uppercase tracking-widest text-white/20">
          Live Data
        </div>
        <p className="font-light text-white/40 max-w-lg leading-relaxed">
          {config.title} data is loaded at runtime from the world state engine. This view
          will populate once connected to a live world instance.
        </p>
        <div className="mt-8 grid grid-cols-3 gap-px border border-white/10">
          {["Entities", "State Updates", "Last Sync"].map((label, i) => (
            <div key={label} className="border-r border-white/10 p-5 last:border-r-0">
              <div className="mb-1 font-mono text-xs uppercase tracking-widest text-white/20">{label}</div>
              <div className="text-xl font-light text-white/40">
                {i === 0 ? "—" : i === 1 ? "0/s" : "Never"}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
