import Link from "next/link";

const archetypes = [
  {
    name: "Equilibrium",
    description:
      "A world in perfect balance — resources regenerate as fast as they are consumed. Stable, predictable, ideal for long-term civilizations.",
  },
  {
    name: "Expansion",
    description:
      "A world actively growing — new territories unlock, population rises, and energy surplus fuels rapid development.",
  },
  {
    name: "Decay",
    description:
      "A world in graceful decline — entropy accumulates, resources thin, and civilizations must adapt or collapse.",
  },
  {
    name: "Cycle",
    description:
      "A world that pulses — boom and bust rhythms encoded into physics. Civilizations learn to ride the wave or perish.",
  },
  {
    name: "Threshold",
    description:
      "A world at the edge — one decision away from transformation. Tipping points define its entire existence.",
  },
  {
    name: "Fork",
    description:
      "A world that splits — divergent timelines emerge from pivotal moments, each branch fully sovereign.",
  },
  {
    name: "Collapse",
    description:
      "A world approaching terminal state — final lessons extracted before the end. Collapse is not failure; it is completion.",
  },
];

const primitives = [
  {
    title: "World DNA",
    description:
      "Each world carries a genetic signature — encoded constraints, tendencies, and evolutionary potential that define its fundamental character.",
  },
  {
    title: "Reality Energy",
    description:
      "The universal currency of existence. Generated by activity, consumed by complexity. Worlds that run out of energy cease to exist.",
  },
  {
    title: "Stakeholder NFTs",
    description:
      "Ownership is fractional and sovereign. NFT holders govern, earn, and shape the destiny of their worlds.",
  },
  {
    title: "Constraint",
    description:
      "Rules are not limitations — they are the architecture of meaning. Every world operates within its own inviolable constraints.",
  },
];

const valueFlow = [
  {
    step: "01",
    title: "Creator mints world",
    description:
      "A new sovereign digital world is initialized with its DNA, constraints, and initial energy allocation.",
  },
  {
    step: "02",
    title: "World generates activity",
    description:
      "Inhabitants, events, commerce, and civilization create Reality Energy — the measure of a world's vitality.",
  },
  {
    step: "03",
    title: "Stakeholders receive revenue",
    description:
      "NFT holders earn proportional revenue from their world's energy generation and commerce activity.",
  },
  {
    step: "04",
    title: "Platform extracts gas fee",
    description:
      "A minimal infrastructure fee sustains the operating system that keeps all worlds alive.",
  },
];

export default function HomePage() {
  return (
    <div className="px-12 py-16 max-w-7xl">
      {/* Header */}
      <header className="mb-32 md:mb-48">
        <div className="mb-16 flex items-center justify-between">
          <div className="font-mono text-sm uppercase tracking-widest text-white/40">
            WORLDS
          </div>
          <Link href="/mint">
            <button className="border border-white/20 bg-transparent font-mono text-xs uppercase tracking-widest text-white/60 hover:text-white hover:border-white/40 px-4 py-2 rounded transition-colors">
              MINT A WORLD
            </button>
          </Link>
        </div>
        <h1 className="max-w-5xl text-balance text-5xl font-light leading-[1.1] tracking-tight md:text-7xl lg:text-8xl text-white">
          We don&apos;t scale users. We scale worlds.
        </h1>
      </header>

      {/* Operating System section */}
      <section className="mb-32 md:mb-48">
        <div className="mb-8">
          <h2 className="font-mono text-xs uppercase tracking-widest text-white/30 mb-6">
            OPERATING SYSTEM
          </h2>
          <p className="text-xl font-light text-white/70 max-w-2xl leading-relaxed">
            An infrastructure for sovereign digital worlds. Each world is fully
            isolated with its own physics, economy, and lifecycle.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-px border border-white/10">
          <div className="p-8 border-r border-white/10">
            <div className="font-mono text-xs uppercase tracking-widest text-white/30 mb-3">
              Isolation
            </div>
            <p className="text-sm text-white/50 leading-relaxed">
              Each world exists in complete isolation. No cross-contamination,
              no shared state, no dependency on other worlds.
            </p>
          </div>
          <div className="p-8 border-r border-white/10">
            <div className="font-mono text-xs uppercase tracking-widest text-white/30 mb-3">
              Sovereignty
            </div>
            <p className="text-sm text-white/50 leading-relaxed">
              World creators and stakeholders define the rules. The platform
              enforces — it does not govern.
            </p>
          </div>
          <div className="p-8">
            <div className="font-mono text-xs uppercase tracking-widest text-white/30 mb-3">
              Lifecycle
            </div>
            <p className="text-sm text-white/50 leading-relaxed">
              Worlds are born, evolve, and die on their own terms. Every ending
              is encoded in the beginning.
            </p>
          </div>
        </div>
      </section>

      {/* Core Primitives */}
      <section className="mb-32 md:mb-48">
        <h2 className="font-mono text-xs uppercase tracking-widest text-white/30 mb-12">
          CORE PRIMITIVES
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {primitives.map((primitive) => (
            <div
              key={primitive.title}
              className="border border-white/10 p-8 hover:border-white/20 transition-colors"
            >
              <h3 className="text-lg font-light text-white mb-3">
                {primitive.title}
              </h3>
              <p className="text-sm text-white/50 leading-relaxed">
                {primitive.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Canonical World Archetypes */}
      <section className="mb-32 md:mb-48">
        <h2 className="font-mono text-xs uppercase tracking-widest text-white/30 mb-12">
          CANONICAL WORLD ARCHETYPES
        </h2>
        <div className="space-y-px border border-white/10">
          {archetypes.map((archetype, i) => (
            <div
              key={archetype.name}
              className="flex items-start gap-8 p-8 border-b border-white/10 last:border-b-0 hover:bg-white/[0.02] transition-colors"
            >
              <div className="font-mono text-xs text-white/20 pt-1 w-8 flex-shrink-0">
                {String(i + 1).padStart(2, "0")}
              </div>
              <div className="flex-1">
                <h3 className="text-base font-light text-white mb-2">
                  {archetype.name}
                </h3>
                <p className="text-sm text-white/50 leading-relaxed">
                  {archetype.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Value Flow */}
      <section className="mb-32 md:mb-48">
        <h2 className="font-mono text-xs uppercase tracking-widest text-white/30 mb-12">
          VALUE FLOW
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-px border border-white/10">
          {valueFlow.map((item) => (
            <div
              key={item.step}
              className="p-8 border-r border-white/10 last:border-r-0"
            >
              <div className="font-mono text-2xl text-white/10 mb-4">
                {item.step}
              </div>
              <h3 className="text-sm font-light text-white mb-3">
                {item.title}
              </h3>
              <p className="text-xs text-white/40 leading-relaxed">
                {item.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section>
        <div className="border border-white/10 p-12 text-center">
          <h2 className="text-3xl font-light text-white mb-4">Mint a World</h2>
          <p className="text-sm text-white/40 mb-8 max-w-md mx-auto">
            Create your sovereign digital world. Define its physics, seed its
            constraints, and watch it evolve.
          </p>
          <Link href="/mint">
            <button className="border border-white/30 bg-transparent font-mono text-xs uppercase tracking-widest text-white hover:bg-white hover:text-black px-8 py-3 rounded transition-colors">
              BEGIN MINTING
            </button>
          </Link>
        </div>
      </section>
    </div>
  );
}
