import { PageHeader } from "@/components/page-header";

const stats = [
  { label: "Generated", value: "12,847", unit: "RE", sub: "System-wide total" },
  { label: "Consumed", value: "9,234", unit: "RE", sub: "Irreversible deductions" },
  { label: "Net Flow", value: "+3,613", unit: "RE", sub: "Current balance" },
  { label: "Efficiency", value: "82", unit: "%", sub: "Galaxy average" },
];

const sources = [
  {
    name: "Participation",
    desc: "Generated by active entity interactions within world boundaries",
    rate: "2.4 RE/hr",
    efficiency: "87%",
  },
  {
    name: "Commerce",
    desc: "Economic transactions and resource exchanges produce energy as byproduct",
    rate: "5.1 RE/hr",
    efficiency: "92%",
  },
  {
    name: "Locked Capital",
    desc: "Staked assets generate low-rate passive energy through commitment",
    rate: "1.8 RE/hr",
    efficiency: "78%",
  },
];

const sinks = [
  { name: "World Edits", desc: "Modifying world parameters or DNA constraints", cost: "120 RE", freq: "On-demand" },
  { name: "Event Creation", desc: "Spawning new entities or triggering state transitions", cost: "85 RE", freq: "Per event" },
  { name: "Complexity Overhead", desc: "Maintaining coherent state across all world systems", cost: "3.2 RE/hr", freq: "Continuous" },
];

const modifiers = [
  { range: "90–100%", multiplier: "1.25×", status: "Optimal", effect: "Maximum generation rates" },
  { range: "70–89%", multiplier: "1.00×", status: "Nominal", effect: "Standard rates apply" },
  { range: "50–69%", multiplier: "0.75×", status: "Degraded", effect: "Reduced generation" },
  { range: "Below 50%", multiplier: "0.50×", status: "Critical", effect: "Minimal energy output" },
];

export default function EnergyPage() {
  return (
    <div className="mx-auto max-w-7xl px-6 py-12">
      <PageHeader
        category="Reality Energy Accounting"
        title="Energy Marketplace"
        description="Generation, consumption, and efficiency metrics"
      />

      {/* Stats */}
      <div className="mb-16 grid gap-px border border-white/10 md:grid-cols-4">
        {stats.map((s) => (
          <div key={s.label} className="border-r border-white/10 p-6 last:border-r-0">
            <div className="mb-2 font-mono text-xs uppercase tracking-widest text-white/30">
              {s.label}
            </div>
            <div className="text-3xl font-light text-white">
              {s.value} <span className="text-xl">{s.unit}</span>
            </div>
            <div className="mt-2 font-mono text-xs text-white/40">{s.sub}</div>
          </div>
        ))}
      </div>

      {/* Sources */}
      <section className="mb-16">
        <h2 className="mb-6 text-sm font-mono uppercase tracking-widest text-white/30">
          Energy Sources
        </h2>
        <div className="space-y-px border border-white/10">
          {sources.map((s) => (
            <div key={s.name} className="border-b border-white/10 p-6 last:border-b-0 hover:bg-white/[0.02] transition-colors">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <div className="text-lg font-light text-white mb-1">{s.name}</div>
                  <div className="font-mono text-xs text-white/50">{s.desc}</div>
                </div>
                <div className="text-right">
                  <div className="text-xl font-light text-white">{s.rate}</div>
                  <div className="font-mono text-xs text-white/30">Generation Rate</div>
                </div>
              </div>
              <div className="border-t border-white/10 pt-4 flex items-center justify-between">
                <div className="font-mono text-xs uppercase tracking-widest text-white/30">Efficiency</div>
                <div className="text-lg font-light text-white">{s.efficiency}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Sinks */}
      <section className="mb-16">
        <h2 className="mb-6 text-sm font-mono uppercase tracking-widest text-white/30">
          Energy Sinks
        </h2>
        <div className="space-y-px border border-white/10">
          {sinks.map((s) => (
            <div key={s.name} className="border-b border-white/10 p-6 last:border-b-0 hover:bg-white/[0.02] transition-colors">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <div className="text-lg font-light text-white mb-1">{s.name}</div>
                  <div className="font-mono text-xs text-white/50">{s.desc}</div>
                </div>
                <div className="text-right">
                  <div className="text-xl font-light text-white/80">{s.cost}</div>
                  <div className="font-mono text-xs text-white/30">Energy Cost</div>
                </div>
              </div>
              <div className="border-t border-white/10 pt-4 flex items-center justify-between">
                <div className="font-mono text-xs uppercase tracking-widest text-white/30">Frequency</div>
                <div className="text-lg font-light text-white">{s.freq}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Efficiency Modifiers */}
      <section className="mb-16">
        <h2 className="mb-6 text-sm font-mono uppercase tracking-widest text-white/30">
          Efficiency Modifiers by World Health
        </h2>
        <div className="border border-white/10">
          <div className="grid grid-cols-4 border-b border-white/10 px-6 py-3">
            {["Health Range", "Multiplier", "Status", "Effect"].map((h) => (
              <div key={h} className="font-mono text-xs uppercase tracking-widest text-white/20">{h}</div>
            ))}
          </div>
          {modifiers.map((m) => (
            <div key={m.range} className="grid grid-cols-4 border-b border-white/10 px-6 py-4 last:border-b-0 hover:bg-white/[0.02] transition-colors">
              <div className="font-light text-white">{m.range}</div>
              <div className="font-light text-white">{m.multiplier}</div>
              <div className="font-light text-white">{m.status}</div>
              <div className="font-mono text-sm text-white/50">{m.effect}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Constraints */}
      <div className="border border-white/10 bg-white/[0.02] p-8">
        <div className="mb-3 font-mono text-xs uppercase tracking-widest text-white/30">
          System Constraints
        </div>
        <h3 className="mb-4 text-xl font-light text-white">Energy Isolation Protocol</h3>
        <div className="space-y-3 font-mono text-sm text-white/50">
          <p>Energy cannot be transferred between worlds. Each world maintains its own isolated energy reserve.</p>
          <p>No speculative trading mechanisms exist. Energy pricing is deterministic based on activity and health metrics.</p>
          <p className="border-l-2 border-white/20 pl-4 text-white/70">
            Warning: Consumption is irreversible and permanently deducted from world reserves. Generation rates are tied to world health and cannot be artificially inflated.
          </p>
        </div>
      </div>
    </div>
  );
}
